# Generated by Django 3.0.2 on 2022-02-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_Name', models.CharField(max_length=200)),
                ('School_Email', models.EmailField(max_length=200)),
                ('School_Password', models.IntegerField(max_length=200)),
                ('School_address', models.CharField(max_length=200)),
                ('School_phone', models.IntegerField(max_length=200)),
                ('school_id', models.IntegerField(max_length=200)),
            ],
        ),
    ]
