# Generated by Django 3.0.2 on 2022-02-03 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='School_Password',
        ),
        migrations.RemoveField(
            model_name='school',
            name='School_phone',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_id',
        ),
    ]
